#
# bsh-dbus-b15p42n3.yaml -- Interface B/S/H/ oven B15P42N3 (NEFF)
#
# This file has been contributed by
# (C) 2026 stefanhirt
# https://github.com/stefanhirt
#
# More info:
# https://github.com/hn/bsh-home-appliances/discussions/91
#
# (C) 2024-2025 Hajo Noerenberg
# https://www.noerenberg.de/
# https://github.com/hn/bsh-home-appliances
#
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3.0 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.
#

esphome:
  name: bsh-dbus-b15p42n3
  friendly_name: BSH oven B15P42N3

external_components:
  - source: github://hn/bsh-home-appliances@master

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG


# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA3

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bsh-Oven-B15P42N3"
    password: "xxx"

captive_portal:

web_server:
  port: 80
  version: 2
  local: true

output:
  - platform: gpio
    pin: 
      number: GPIO07
      inverted: true
    id: activity_led

uart:
  id: dbus_uart
  rx_pin: GPIO4
  tx_pin: GPIO5
  # needed higher baud_rate
  baud_rate: 19200
  rx_buffer_size: 1024

bshdbus:
  uart_id: dbus_uart
  on_frame:
    - logger.log:
        format: "Received frame dest 0x%02x cmd 0x%04x: 0x%s"
        args: [dest, command, format_hex(message).c_str()]
    - output.turn_on: activity_led
    - delay: 20ms
    - output.turn_off: activity_led

status_led:
  pin:
    number: GPIO06
    inverted: true

binary_sensor:
  - platform: bshdbus
    dest: 0x00
    command: 0x7004
    binary_sensors:
      - id: bsh_oven_standby
        name: An⁄Aus
        device_class: power
        lambda: return (x[0]);
  - platform: bshdbus
    dest: 0x20
    command: 0x7228
    binary_sensors:
      - id: bsh_oven_fan
        name: Gebläse
        icon: mdi:fan
        lambda: return (int16_t) (x[4] -7 );
        # 7.0 -> Heißluftgebläse aus
        # 8.0 -> Heißluftgebläße an
  - platform: bshdbus
    dest: 0x10
    command: 0x720d
    binary_sensors:
      - id: bsh_oven_light
        name: Licht
        device_class: light
        lambda: return (x[1]);
# Has to be investigated further
  - platform: bshdbus
    dest: 0x20
    command: 0x7271
    binary_sensors:
      - id: bsh_oven_heat
        name: Heiß
        device_class: heat
        lambda: return (x[1]);

sensor:
  - platform: bshdbus
    dest: 0x20
    command: 0x7206
    sensors:
      - id: bsh_oven_temperature
        name: Temperatur (Ist)
        icon: mdi:thermometer
        device_class: temperature
        state_class: measurement
        unit_of_measurement: °C
        accuracy_decimals: 0
        lambda: return (int16_t) ((x[1] << 8) | x[2]);
  - platform: bshdbus
    dest: 0x10
    command: 0x7201
    sensors:
      - id: bsh_oven_target_temperature
        name: Temperatur (Soll)
        icon: mdi:thermometer
        device_class: temperature
        state_class: measurement
        unit_of_measurement: °C
        accuracy_decimals: 0
        lambda: return (int16_t) ((x[2] << 8) | x[3]);

text_sensor:
  - platform: bshdbus
    dest: 0x10
    command: 0x7201
    text_sensors:
      - id: bsh_oven_mode
        name: Betriebsart
        icon: mdi:form-select
        lambda: return std::to_string (x[1]);
        filters:
          - map:
            - 0 -> Aus
            - 2 -> Ober-/Unterhitze
            - 5 -> CircoTherm® Heißluft 
            - 6 -> Thermogrillen
            - 7 -> Grill klein
            - 8 -> Grill groß
            - 11 -> Unterhitze
            - 12 -> Pizzastufe
            - 24 -> Sanftgaren
            - 46 -> CircoTherm® Heißluft Eco
            # Pyrolytische Reinigung ?
            # Garraumbeleuchtung ?